### ARRAY CREATING

In [2]:
import numpy as np

In [3]:
oned=np.array([1,5,3])
oned

array([1, 5, 3])

In [4]:
twod=np.array([[3,8,2]])
twod

array([[3, 8, 2]])

In [5]:
#check is the array is actually 2d
twod.ndim


2

In [6]:
threed=np.array([[[1,3,4],[5,9,2],[54,6,2]]])
threed

array([[[ 1,  3,  4],
        [ 5,  9,  2],
        [54,  6,  2]]])

In [7]:
# dtype se data type specify int ko float mein convert
specific_float_array=np.array([[1,2,9],[4,7,3]],dtype=float)
specific_float_array

array([[1., 2., 9.],
       [4., 7., 3.]])

In [8]:
#change array type to int
specific_float_array=specific_float_array.astype("int64")
specific_float_array

array([[1, 2, 9],
       [4, 7, 3]])

In [9]:
#make array with arange
range_array=np.arange(4,11) # start kahse hogi or end kha tak)
range_array

array([ 4,  5,  6,  7,  8,  9, 10])

### Initilize array

In [10]:
ones_array=np.ones((11,6)) #11 rows and 6 colum
ones_array # har jaga one fill

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
#agar float ma nhi ache to
ones_array_int=np.ones((11,6),dtype=int) #11 rows and 6 colum
ones_array # har jaga one fill

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [12]:
#ase he zeros bhi kar sakte or random number bhi 
zeros_array=np.zeros((11,6)) #11 rows and 6 colum
zeros_array # har jaga zeros fill

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
random_num_array=np.random.random((11,5))
random_num_array

array([[0.28327164, 0.04266616, 0.98393219, 0.88424834, 0.99608612],
       [0.18244483, 0.86073209, 0.97010969, 0.04650705, 0.48026922],
       [0.83984456, 0.02914396, 0.32748846, 0.82690452, 0.13133698],
       [0.84477994, 0.83457897, 0.54333656, 0.28543843, 0.0847659 ],
       [0.40745542, 0.8592467 , 0.68923707, 0.74070603, 0.85383365],
       [0.13309737, 0.97374997, 0.10103823, 0.93163304, 0.35595348],
       [0.60514348, 0.11935222, 0.7790442 , 0.64623298, 0.89446785],
       [0.00821797, 0.13750104, 0.87693138, 0.44608763, 0.88729258],
       [0.89373968, 0.8325394 , 0.75150955, 0.82509167, 0.13283613],
       [0.10940686, 0.48040193, 0.2509439 , 0.72487954, 0.08752197],
       [0.51308468, 0.70873467, 0.6851855 , 0.63352768, 0.01189326]])

In [14]:
random_num_array_int=np.random.random((11,5))
random_num_array

array([[0.28327164, 0.04266616, 0.98393219, 0.88424834, 0.99608612],
       [0.18244483, 0.86073209, 0.97010969, 0.04650705, 0.48026922],
       [0.83984456, 0.02914396, 0.32748846, 0.82690452, 0.13133698],
       [0.84477994, 0.83457897, 0.54333656, 0.28543843, 0.0847659 ],
       [0.40745542, 0.8592467 , 0.68923707, 0.74070603, 0.85383365],
       [0.13309737, 0.97374997, 0.10103823, 0.93163304, 0.35595348],
       [0.60514348, 0.11935222, 0.7790442 , 0.64623298, 0.89446785],
       [0.00821797, 0.13750104, 0.87693138, 0.44608763, 0.88729258],
       [0.89373968, 0.8325394 , 0.75150955, 0.82509167, 0.13283613],
       [0.10940686, 0.48040193, 0.2509439 , 0.72487954, 0.08752197],
       [0.51308468, 0.70873467, 0.6851855 , 0.63352768, 0.01189326]])

In [15]:
#wants random numbers in int use randint
random_num_array_int = np.random.randint(0, 10, size=(11,5)) # 0 se 10 ke bbech any value random

random_num_array_int

array([[8, 6, 5, 7, 3],
       [4, 4, 7, 4, 8],
       [0, 4, 3, 6, 5],
       [2, 4, 4, 8, 3],
       [5, 3, 0, 3, 1],
       [7, 8, 8, 6, 2],
       [3, 8, 3, 7, 7],
       [3, 7, 7, 2, 8],
       [9, 7, 2, 1, 8],
       [2, 0, 5, 4, 1],
       [5, 4, 6, 9, 5]], dtype=int32)

In [16]:
#linspace use for equal distane number array
equal_array_num=np.linspace(22,50)
equal_array_num

array([22.        , 22.57142857, 23.14285714, 23.71428571, 24.28571429,
       24.85714286, 25.42857143, 26.        , 26.57142857, 27.14285714,
       27.71428571, 28.28571429, 28.85714286, 29.42857143, 30.        ,
       30.57142857, 31.14285714, 31.71428571, 32.28571429, 32.85714286,
       33.42857143, 34.        , 34.57142857, 35.14285714, 35.71428571,
       36.28571429, 36.85714286, 37.42857143, 38.        , 38.57142857,
       39.14285714, 39.71428571, 40.28571429, 40.85714286, 41.42857143,
       42.        , 42.57142857, 43.14285714, 43.71428571, 44.28571429,
       44.85714286, 45.42857143, 46.        , 46.57142857, 47.14285714,
       47.71428571, 48.28571429, 48.85714286, 49.42857143, 50.        ])

In [17]:
#identity matrix 
identity_matrix=np.identity(6 ,dtype=int) #Diagonal (↘) ke elements 1 hote hainBaaki sab elements 0 hote hain
identity_matrix

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

### ARRAY PROPERTIES

In [18]:
oned.shape


(3,)

In [19]:
oned.size# Total elements count karega


3

In [20]:
threed.itemsize# Ek element kitni memory leta hai

8

In [21]:
threed.dtype# Array ka data type batata hai

dtype('int64')

In [22]:
equal_array_num.dtype

dtype('float64')

In [23]:
equal_array_num

array([22.        , 22.57142857, 23.14285714, 23.71428571, 24.28571429,
       24.85714286, 25.42857143, 26.        , 26.57142857, 27.14285714,
       27.71428571, 28.28571429, 28.85714286, 29.42857143, 30.        ,
       30.57142857, 31.14285714, 31.71428571, 32.28571429, 32.85714286,
       33.42857143, 34.        , 34.57142857, 35.14285714, 35.71428571,
       36.28571429, 36.85714286, 37.42857143, 38.        , 38.57142857,
       39.14285714, 39.71428571, 40.28571429, 40.85714286, 41.42857143,
       42.        , 42.57142857, 43.14285714, 43.71428571, 44.28571429,
       44.85714286, 45.42857143, 46.        , 46.57142857, 47.14285714,
       47.71428571, 48.28571429, 48.85714286, 49.42857143, 50.        ])

In [24]:
equal_array_num.astype("int64")# Array ka type convert karo

array([22, 22, 23, 23, 24, 24, 25, 26, 26, 27, 27, 28, 28, 29, 30, 30, 31,
       31, 32, 32, 33, 34, 34, 35, 35, 36, 36, 37, 38, 38, 39, 39, 40, 40,
       41, 42, 42, 43, 43, 44, 44, 45, 46, 46, 47, 47, 48, 48, 49, 50])

### Array Operations

In [25]:
print(oned)
print(twod)

[1 5 3]
[[3 8 2]]


In [26]:
oned+twod # Same position wale elements add honge
# Dono arrays ki shape same honi chahiye


array([[ 4, 13,  5]])

In [27]:
one=np.array([1,3,6,9])  
one2=np.array([[1,7,9,3,6,9],[1,6,3,8,5,5]])

print(one.shape)
print(one2.shape)


(4,)
(2, 6)


In [28]:
#now we addition different shape of arrays
try:
    one+one2
except:
    print("different shape size cant be add")

different shape size cant be add


In [29]:
oned**twod# Har element ka square hoga
# Ek single value har element pe apply hoti hai


array([[     1, 390625,      9]])

In [30]:
print(oned)
print(twod)

[1 5 3]
[[3 8 2]]


In [31]:
oned-twod #sign bare ka isliye - arah

array([[-2, -3,  1]])

In [32]:
twod-oned

array([[ 2,  3, -1]])

In [33]:
twod==oned

array([[False, False, False]])

### ARRAY FUNCTION

In [34]:
array_fun1 = np.arange(0,20,2,dtype=int).reshape(5,2)
array_fun1 #size array 10 isliye reshpae 5*2=10 

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [ ]:
np.prod(array_fun1,axis=1) 
# [0 2]   → 0×2 = 0
# [4 6]   → 4×6 = 24
# [8 10]  → 8×10 = 80 and so on

array([  0,  24,  80, 168, 288])

In [ ]:
np.sum(array_fun1) 
#0 + 2 + 4 + 6 + 8 + 10 + 12 + 14 + 16 + 18=90

np.int64(90)

In [ ]:
print(np.max(array_fun1)) #arrayy ki sab se bari value

18


In [44]:
print(np.min(array_fun1)) #arrayy ki sab se small value

0


In [46]:
print(np.mean(array_fun1)) 
print(np.median(array_fun1))
print(np.std(array_fun1))

9.0
9.0
5.744562646538029


In [47]:
np.var(array_fun1, axis=1)

array([1., 1., 1., 1., 1.])

In [53]:
print(np.sin(array_fun1))
print("sin RESULT\n")
print(np.exp(array_fun1))
print("sin RESULT\n")


[[ 0.          0.90929743]
 [-0.7568025  -0.2794155 ]
 [ 0.98935825 -0.54402111]
 [-0.53657292  0.99060736]
 [-0.28790332 -0.75098725]]
sin RESULT

[[1.00000000e+00 7.38905610e+00]
 [5.45981500e+01 4.03428793e+02]
 [2.98095799e+03 2.20264658e+04]
 [1.62754791e+05 1.20260428e+06]
 [8.88611052e+06 6.56599691e+07]]
sin RESULT



In [66]:
array_fun2=np.arange(1,16).reshape(3,5)
print(array_fun2)
array_fun3=np.arange(1,16).reshape(5,3)
print(array_fun3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [72]:
array_fun4=np.random.random((3,5))

In [ ]:
print("dot product result")  
# matrix multiplication (rows × columns combine karke result nikalta hai)
print(np.dot(array_fun2, array_fun3))

print("ceil function result")  
# har value ko upar wale nearest integer par round karta hai
print(np.ceil(array_fun4))

print("floor function result") 
# har value ko neeche wale nearest integer par round karta hai
print(np.floor(array_fun4))

print("round function result")  
# normal rounding (0.5 se upar ho to +1, warna same)
print(np.round(array_fun4))

dot product resut
[[135 150 165]
 [310 350 390]
 [485 550 615]]
ceil function resut
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
floor function resut
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
round function resut
[[0. 0. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]


### INDEXING AND SLICING

In [77]:
for_index_and_slice=np.arange(1,36).reshape(5,7)
for_index_and_slice

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35]])

In [80]:
#fetch 11
for_index_and_slice[1,3] #row then colum


np.int64(11)

In [85]:
#for 3d array we need 1 more value (matrix , row , column)
for_index_3d=np.arange(1,19).reshape(3,3,2)#3×3×2=18
for_index_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [87]:
#fetch second 2d matix element 10
for_index_3d[1,1,1]

np.int64(10)

In [88]:
for_index_and_slice

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35]])

In [ ]:
#slicing middle 3 rows aur middle 3 columns nikaalo
for_index_and_slice[1:4, 2:5] 
#1:4 means rows 1,2,3
# 2:5 means columns 2,3,4

array([[10, 11, 12],
       [17, 18, 19],
       [24, 25, 26]])

In [101]:
for_index_and_slice


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35]])

In [100]:
for_index_and_slice[::2, 2:5] 
# Matlab:

# start se leke end tak
# 2 step jump (skip 1 row)

# Rows selected:

# row 0 → yes
# row 1 → skip
# row 2 → yes
# row 3 → skip
# row 4 → yes

array([[ 3,  4,  5],
       [17, 18, 19],
       [31, 32, 33]])

In [104]:
for_index_and_slice[::3, 2:3]

# Matlab:

# start se end tak
# 3 step jump (2 rows skip)

# Rows select honge:

# index 0 → row 1
# index 3 → row 4
# index 6 exist nahi

array([[ 3],
       [24]])

In [105]:
for_index_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [ ]:
#slicing on 3d array
for_index_3d[::2, 0, ::2]#alternate blocks + first row + alternate columns

array([[ 1],
       [13]])

### ITERATING ARRAY

In [107]:
array_fun1

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [110]:
a1=np.arange(1,17)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
#1d array
for i in a1:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [ ]:
#2d array
for i in array_fun1:
    print(i)

[0 2]
[4 6]
[ 8 10]
[12 14]
[16 18]


In [114]:
#3d array pe iteration ke liye method lagana parta ha
for_index_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [ ]:
#3d array pe iteration ke liye method lagana parta ha
for i in np.nditer(for_index_3d):
    print(i)

#Ye poora 3D array ko 1D bana deta hai internally
#Phir har element ek ek karke print karta hai

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18


### reshaping array

In [119]:
for_index_and_slice

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35]])

In [ ]:
for_index_and_slice.T 

#column ko row ma and row ko column ma kardeta ha 

array([[ 1,  8, 15, 22, 29],
       [ 2,  9, 16, 23, 30],
       [ 3, 10, 17, 24, 31],
       [ 4, 11, 18, 25, 32],
       [ 5, 12, 19, 26, 33],
       [ 6, 13, 20, 27, 34],
       [ 7, 14, 21, 28, 35]])

In [121]:
np.transpose(for_index_and_slice)

array([[ 1,  8, 15, 22, 29],
       [ 2,  9, 16, 23, 30],
       [ 3, 10, 17, 24, 31],
       [ 4, 11, 18, 25, 32],
       [ 5, 12, 19, 26, 33],
       [ 6, 13, 20, 27, 34],
       [ 7, 14, 21, 28, 35]])

In [125]:
print(for_index_3d)

print("use ravel which convert any demsion array to 1D")
for_index_3d.ravel()

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
use ravel which convert any demsion array to 1D


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

### STacking array (is ke liye dono arrays ka size same hona chaye)

 hstack → columns add karta hai  rows same honi chahiye

vstack → rows add karta hai  columns same honi chahiye 

In [147]:
for_index_and_slice

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35]])

In [ ]:
for_stack_2=np.arange(30,65).reshape(5,7)
for_stack_2


2

In [ ]:
np.hstack((for_index_and_slice,for_stack_2))
#rows kitne te uste rahe column change

array([[ 1,  2,  3,  4,  5,  6,  7, 30, 31, 32, 33, 34, 35, 36],
       [ 8,  9, 10, 11, 12, 13, 14, 37, 38, 39, 40, 41, 42, 43],
       [15, 16, 17, 18, 19, 20, 21, 44, 45, 46, 47, 48, 49, 50],
       [22, 23, 24, 25, 26, 27, 28, 51, 52, 53, 54, 55, 56, 57],
       [29, 30, 31, 32, 33, 34, 35, 58, 59, 60, 61, 62, 63, 64]])

In [ ]:
np.vstack((for_index_and_slice,for_stack_2))
#colum kitne te uste rahe rows change

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63, 64]])

### splitting array

hsplit=axis=1 (columns split only)

split + axis=1=manual control (rows or columns both possible)

hsplit → horizontal (columns)

vsplit → vertical (rows)

split + axis → flexible (don’t care direction)

In [164]:
split_1=np.arange(50,86).reshape(6,6)
split_1

array([[50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61],
       [62, 63, 64, 65, 66, 67],
       [68, 69, 70, 71, 72, 73],
       [74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85]])

In [ ]:
np.vsplit(split_1,2)
# ka matlab hota hai:
# rows ko 2 equal parts me todna
# array ko 2 equal parts me divide karo
#np.split=equal division required along axis

[array([[50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61],
        [62, 63, 64, 65, 66, 67]]),
 array([[68, 69, 70, 71, 72, 73],
        [74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85]])]

In [168]:
np.hsplit(split_1,2)

[array([[50, 51, 52],
        [56, 57, 58],
        [62, 63, 64],
        [68, 69, 70],
        [74, 75, 76],
        [80, 81, 82]]),
 array([[53, 54, 55],
        [59, 60, 61],
        [65, 66, 67],
        [71, 72, 73],
        [77, 78, 79],
        [83, 84, 85]])]

In [171]:
split_1

array([[50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61],
       [62, 63, 64, 65, 66, 67],
       [68, 69, 70, 71, 72, 73],
       [74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85]])

In [ ]:
np.split(split_1, 2, axis=1)
#axis=1 column ko 2 eaqual part ma divide 

[array([[50, 51, 52],
        [56, 57, 58],
        [62, 63, 64],
        [68, 69, 70],
        [74, 75, 76],
        [80, 81, 82]]),
 array([[53, 54, 55],
        [59, 60, 61],
        [65, 66, 67],
        [71, 72, 73],
        [77, 78, 79],
        [83, 84, 85]])]

In [172]:
np.split(split_1, 2, axis=0)

[array([[50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61],
        [62, 63, 64, 65, 66, 67]]),
 array([[68, 69, 70, 71, 72, 73],
        [74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85]])]